### ISSUE TITLE
setPixelsRaw does nothing?

### ISSUE THREAD

**Issue by gamax92** [ds84182/CCLights2#18]
I've tried this:
`gpu.setPixelsRaw(1,1,100,100,{255,255,255,255})`

```
java.lang.NullPointerException
at ds.mods.CCLights2.converter.ConvertDouble.convert(ConvertDouble.java:9)
at ds.mods.CCLights2.converter.ConvertInteger.convert(ConvertInteger.java:6)
at ds.mods.CCLights2.block.tileentity.TileEntityGPU.callMethod(TileEntityGPU.java:362)
...
```

EDIT: Also if you don't pass a table you get:
`java.lang.Double cannot be cast to java.util.Map`

EDIT2: So .. I noticed it started from 0 to (w_h_4)-1, tried:
`gpu.setPixelsRaw(1,1,100,100,{[0]=255,255,255,255})`
`java.lang.Short cannot be cast to java.lang.Integer`

EDIT3: Also I can't build CCLights2 `;-;`

**Comment by ds84182** [comment]
What code did you use so I can reproduce it?

**Comment by ds84182** [comment]
ohwait, I see, god damn it GMail

**Comment by ds84182** [comment]
gamax, you were calling the method wrong, but I am going to change the arguments to the method to match common standards better.

**Comment by alekso56** [comment]
No, he called it right. so im making this and all related raw methods deprecated. that means gpu.setPixelsRaw() ,gpu.setPixelsRawYX(), is hereby deprecated.

if you want to import stuff, use gpu.import(), or use gpu.setColor(), gpu.plot() because it's accelerated now

 (#bestsolution #crappyCommandsDontevenwork.)

**Comment by alekso56** [comment]
Okay, implemented your changes gamax, and renamed it to setPixels()
